version: '3.7'
services:
  auth_db:
    container_name: auth-db
    image: postgres
    restart: on-failure
    ports:
      - 5002:5432
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
