version: '3.7'
services:
  auth:
    networks:
      - last-message-backend
    container_name: secure
    image: secure
    build: .
    ports:
      - 8082:8082
    depends_on:
      - auth_db
  auth_db:
    container_name: auth-db
    image: postgres
    restart: on-failure
    networks:
      - last-message-backend
    ports:
      - 5002:5432
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
networks:
  last-message-backend:
    name: last-message-backend